# Generated by Django 4.1.2 on 2022-11-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['isbn'], 'permissions': (('can_edit_book', 'Create, Update and Delete books'),)},
        ),
    ]
